<?php if (count($this->messages) > 0): ?>
    <div class="row">
        <div class="col-sm-4 col-sm-offset-4">
            <div class="alert alert-danger">
                <ul>
                    <?php foreach ($this->messages as $message): ?>
                        <li>
                            <?= $message ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>
<?= $this->form()->openTag($form) ?>
<?= $this->formElement($form->get($form->getName() . '_csrf')) ?>
<div class="row">
    <div class="form-group">
        <div class="col-sm-4 col-sm-offset-4">
            <?= $this->formElement($form->get('identity')) ?>
        </div>
    </div>
</div>
&nbsp;
<div class="row">
    <div class="form-group">
        <div class="col-sm-4 col-sm-offset-4">
            <?= $this->formElement($form->get('submit')) ?>
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>